/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csx55.threads;

import csx55.threads.Node.ComputeNodeRunner;
import csx55.threads.Node.Node;


import java.io.IOException;
import java.net.ServerSocket;
import java.util.Scanner;


public class ComputeNode {

    private Node myNode;
    private Thread nodeThread = null;

    public static void main(String[] args) throws IOException, InterruptedException {
        
        if (args.length < 1){
            //ln("Error, no args specified");
            System.exit(0);
        }
        if (args.length < 2){
            //System.out.println("Error, no port selected");
            System.exit(0);
        }

        ComputeNode myCompute  = new ComputeNode();

        //make a mess, to use it later
        
        //parse arguments
        int regPortNumber = Integer.parseInt(args[1]); 
        String regHostname = (args[0]); 

        //System.err.println(regHostname);
        
        String name = "MessagingNode"; 
        try {

            //This starts the listening node
            int myPortNumber = myPort();
            myCompute.myNode = new ComputeNodeRunner(name, myPortNumber, regHostname, regPortNumber);
           
            myCompute.nodeThread = new Thread(myCompute.myNode);
            myCompute.nodeThread.start();
            
            //cmdlineThread.start();
            Scanner scanner = new Scanner(System.in);
            Boolean scan = true;

            //System.out.print("Command Awaiting: ");
            while(scan){
                try{
                    String cmd = scanner.nextLine();
                    //System.out.println("Command Recieved: " + cmd);
                    clientCommandHandler(cmd, myCompute.myNode);
                    if (cmd.equals("exit")){
                        scan = false;
                    }
                    //System.out.print("Command Awaiting: ");
                    
                }
                catch (Exception e){
                    
                }
                
            }
            //System.out.println("Past loop");

            //node.shutdown();
            //nodeThread.join();            
            scanner.close();

            //System.out.println("Closing");
           


            //TODO make this its own thread, lets do that tomorrow

            //node.run();
            //Todo clean shut down

            
        } catch (Error e) {
            e.printStackTrace();
            //serverSocket.close();
        }

        
    }

    public static int myPort(){
        //point of this method is to onstartup, determine what our port will be. Our low bar will be 22600, arbitrary choice

            try (ServerSocket serverSocket = new ServerSocket(0)) {
                return serverSocket.getLocalPort();
            } catch (IOException e) {
                
            }
        //}
        throw new IllegalStateException("No free port found within the range, contact your admin");
        

    }

    public static void clientCommandHandler(String command, Node node){
        String[] commandBroken = command.split("\\s+");
        
        switch (commandBroken[0].toString()){
            case "Cm":
                node.showConnections();
                break;

            case "exit-overlay":
                //deregister(mess);
                break;
        }

    }

    //may need dereg in the future


}
